---
title: "final_vehicle_result"
output: html_document
---

```{r}
library(tidyverse)
library(tidymodels)
library(ggplot2)

load('data/btree_tune.rda')
load('data/svmrb_tuned.rda')
load('data/vehicle_setup.rda')
load('data/vehicles_strat.rda')
load('data/vehicles.rda')
load('data/rf_tune.rda')
```


# Four model results

```{r, error=TRUE}
tune_results <- 
  tibble(
    model_type = 
      c(
        "rf", 
        "bt", 
        "svmrb"),
    tune_info = list(
        # nn_tuned, 
        rf_tune, 
        btree_tune,
        svmrb_tuned
      ),
    assessment_info = 
      map(
      tune_info, collect_metrics
      ),
    best_model = 
      map(
        tune_info,
        ~ select_best(.x, metric = "rmse")
      )
  )

tune_results

tune_results %>%
  select(model_type, assessment_info) %>%
  unnest(assessment_info) %>%
  filter(.metric == "rmse") %>%
  arrange(mean)
```

```{r}
rf_tune %>% 
  autoplot(metric = "rmse")


svmrb_tuned %>%
  autoplot(metric = 'rmse')

btree_tune %>%
  autoplot(metric = 'rmse')
  
```


